#!/bin/bash
# Function to check the server type
check_server_type() {
    if [ -f "/etc/redhat-release" ]; then
        SERVER_TYPE="Red Hat"
    elif [ -f "/etc/lsb-release" ]; then
        SERVER_TYPE="Ubuntu"
    else
        SERVER_TYPE="Unknown"
    fi
    echo "Server type: $SERVER_TYPE"
}
 # ps aux = list all processes
 # --sort = %cpu sort the process based on cpu
# Function to check top processes
check_top_processes() {
    echo "Checking top 5 processes for $1..."

    # Check top CPU-consuming processes
    echo -e "\nTop 5 processes by CPU usage:"
    ps aux --sort=-%cpu | head -6

    # Check top memory-consuming processes
    echo -e "\nTop 5 processes by memory usage:"
    ps aux --sort=-%mem | head -6
}
check_server_type
check_top_processes
